# Generated by Django 3.1.6 on 2021-02-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
