# Generated by Django 3.1.6 on 2021-02-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_delete_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive_file',
            old_name='file_name_full_text',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='archive_file',
            old_name='hours_worked_float',
            new_name='hours_worked',
        ),
    ]
